import { defineStore } from "pinia";

export const useAttendancesStore = defineStore("attendance", {
  state: () => ({
    number: 0,
    attendances: [
      {
        id: 0,
        name: "Husni Mubarok",
        class_id: "klsvii",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "late",
      },
      {
        id: 1,
        name: "Fery",
        class_id: "klsviii",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian Rizal Maulana dsadsads",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
      {
        id: 2,
        name: "Rian",
        class_id: "klsix",
        date: new Date(2022, 9, 27).toLocaleDateString(),
        in: "08:00",
        out: "12:00",
        status: "ontime",
      },
    ],
  }),
  getters: {
    getAttendance: (state) => {
      return state.attendances.sort();
    },
  },
  actions: {
    addAttendance(data) {
      this.attendances.unshift(data);
      // console.log(data);
    },
  },
});
